### ISSUE TITLE
Values of Pagerank quickly increase for each iteration, and does not match GraphChi

### ISSUE THREAD

**Issue by abh3hu** [M-Flash/m-flash-cpp#1]
I ran Pagerank on a 12 vertices and 26 edges graph and checked the results in 'pg'. With each iteration, the values grew by the hundreds. With 10 iterations, the values were 'inf'

**Comment by dejesus8907** [comment]
hello Hugo, I was wondering  if you had a chance to look into the above issue?

**Comment by hagc2812** [comment]
Sorry for the delay. I am debugging the code. Please, share me your input.

**Comment by abh3hu** [comment]
Input File:
0 4
0 7
0 8
1 7
2 7
3 5
3 6
4 0
4 5
4 7
5 3
5 4
5 6
6 3
6 5
7 0
7 1
7 2
7 4
8 0
8 9
8 10
8 11
9 8
10 8
11 8

Output with 4 Iterations
635.703
237.54
237.54
201.664
496.796
306.56
201.664
363.986
203.572
232.013
232.013
232.013

**Comment by dejesus8907** [comment]
Hugo, thanks for responding so quickly, Im excited to test the code again when your done...
